---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - config-map.yaml
  - statefulset.yaml
  - services.yaml
  - route.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: elastic
    type: stringData
    env: secret.env
